---
title: "Selected Publications"
---

***

**Publications under review**

-	**_Wijerathna-Yapa, A._**, Isaac, K.S., Combe, M., Hume, S., and Sokolenko, S. (2025). Re-imagining Human Cell Culture Media: Challenges, Innovations, and Future Directions. Biotechnology Advances (JBA-D-24-01213)
-	Isaac, K.S., Leb, P. M., Street, T., **_Wijerathna-Yapa, A._**, and Sokolenko, S. (2025). Advancing Quantitative NMR for High-Precision Isotopic Analysis with rnmrfit 2.0. Analytical Chemistry.


**Peer-reviewed Scientific Journal Articles**

_**Biochemistry and Omics**_

- Pri-Tal, O., Sun, Y., Dadras, A., Fürst-Jansen, J.M.R., Zimran, G., Michaeli, D., **_Wijerathna-Yapa, A._**, Shpilman, M., Merilo, E., Yarmolinsky, D., Efroni, I., de Vries, J., Kollist, H. and Mosquna, A. (2024), Constitutive activation of ABA receptors in Arabidopsis reveals unique regulatory circuitries. New Phytol, 241: 703-714. https://doi.org/10.1111/nph.19363.
- Li, L., Lee, C. P., Ding, X., Qin, Y., **_Wijerathna-Yapa, A._**, Broda, M., Otegui, M. S., Ganguly, D.R., Pogson, B.J., and Millar. H. (2022). Defects in autophagy lead to selective in vivo changes in turnover of cytosolic and organelle proteins in roots and shoots of Arabidopsis. The Plant Cell, koac185, https://doi.org/10.1093/plcell/koac185
- Li, L., Duncan, O., Ganguly, D.R., Lee, C.P., Crisp, P., **_Wijerathna-Yapa, A._**, Pogson, B.J., Salih, K., - Trosch, J., Millar, A.H., and Pogson, B.J. (2022). Metabolic enzymes degraded under high light stress - maintain their proteostasis by coupled transcriptional regulation in Arabidopsis. Proceedings of the National Academy of Sciences 119(20) e2121362119.doi: https://doi.org/10.1073/pnas.2121362119
- **_Wijerathna-Yapa, A._**, Signorelli, S., Fenske, R., Ganguly, D.R., Stroeher, F., Li,L., Pogson, B.J., Duncan, O., and Millar. H. (2021). Autophagy mutants show delayed chloroplast development during de-etiolation in carbon limiting conditions. The Plant Journal. doi: https://doi.org/10.1111/tpj.15452
- **_Wijerathna-Yapa, A._**, Stroeher, E., Fenske,R., Li, L., Duncan, O., and Millar, H. (2020). Proteomics for Autophagy Receptor and Cargo Identification in Plants. J. Proteome Res. American Chemical Society. doi: https://doi.org/10.1021/acs.jproteome.0c00609

_**Biotechnology**_

- Carra, A., **_Wijerathna-Yapa, A._**, Pathirana, R., & Carimi, F. (2024). Development and applications of somatic embryogenesis in grapevine (Vitis spp.). Plants, 13(22), 3131.  https://doi.org/10.3390/plants13223131
- **_Wijerathna-Yapa, A._**, Bishnoi, R., Ranawaka, B., Magar, M.M., Rehman, H.U., Bharad, S.G., Lorenc, M.T., Ramtekey, V., Gohar, S., Lata, C. and Harun-Or-Rashid, M., Razzaq, M., Sajjad, M., and Basnet, B.R. (2023). Rice–wheat comparative genomics: Gains and gaps. The Crop Journal, 12(3), 656-669. https://doi.org/10.1016/j.cj.2023.10.008
- **_Wijerathna-Yapa, A._**, and Hiti-Bandaralage, J. 2023. Tissue Culture—A Sustainable Approach to Explore Plant Stresses. Life, 13(3), 780. https://doi.org/10.3390/life13030780
- **_Wijerathna-Yapa, A._**, Ramtekey, V., Ranawaka, B., Basnet, B.R. (2022). Applications of In Vitro Tissue Culture Technologies in Breeding and Genetic Improvement of Wheat. Plants, 11(17):2273. https://doi.org/10.3390/plants11172273
- Sun, Y., Harpazi, B., **_Wijerathna-Yapa, A._**, Merilo, E., de Vries, J., Michaeli, D., Gal, M., Cuming, A., - Kollist, H. and Mosquna, A. (2019). A ligand-independent origin of abscisic acid perception. Proceedings of the National Academy of Science. National Academy of Sciences. 116 (49) 24892-24899.doi: https://doi.org/10.1073/pnas.1914480116
- **_Wijerathna-Yapa, A._** (2017). Transgenic plants: resistance to abiotic and biotic stresses.  JAEID, 111 (1): 245-275.doi: https://doi.org/10.12895/jaeid.20171.643
- **_Wijerathna, Y.M.A.M._** and Kumarihami H.M.P.C. (2016). Effects of Different Hormonal Concentrations and - Culture Medium on Multiplication and Rooting of Stage II Banana (_Musa cavendishii_). Not Sci Biol, 8(1):69-72. doi: https://doi.org/10.15835/nsb819749
- **_Wijerathna, Y.M.A.M._** (2015). Marker-Assisted Selection: Biotechnology Tool for Rice Molecular Breeding. Adv Crop Sci Tech 3: 187. doi:10.4172/2329-8863.1000187.
- **_Wijerathna, Y.M.A.M._** (2015). Application of Biotechnology in Coconut (Cocos nucifera L.): Sri Lanka. Plant Tissue Cult. & Biotech. 25(1): 103‐116. doi: https://doi.org/10.3329/ptcb.v25i1.24130
- **_Wijerathna, Y.M.A.M._**, Perera, A.N.K.,Hamamah,I.B. and Hoang Long. (2015). Application of PCR and MAS: - Potential Use for Assessment of Genetic Diversity of Rice Germplasm in Breeding Programs in Developing Countries. Pertanika J. Trop. Agric. Sci. 38 (2): 161 – 174. [JTAS-0613-2014](http://www.pertanika.upm.edu.my/resources/files/Pertanika%20PAPERS/JTAS%20Vol.%2038%20(2)%20May.%202015/01%20Page%20161-174%20(JTAS%200613-2014).pdf)
- **_Wijerathna, Y.M.A.M._**, Kottearachchi, N.S.,Gimhani, D.R. and Sirisena, D.N. (2014). Exploration of Relationship between Fragrant Gene and Growth Performances of Fragrant Rice (Oryza Sativa L.) Seedlings under Salinity Stress. Journal of Experimental Biology and Agricultural Sciences. 2 (1):7-12.[Corpus ID: 81504175](http://www.jebas.org/wp-content/uploads/2014/09/Kottearachchi-et-al-JEBAS.pdf)
- **_Wijerathna, Y.M.A.M._** (2012). Advances of Basic Molecular Biology Techniques: Potential to Apply in Plant - Viroid Detection in Sri Lanka. eSci J. Plant Pathol. 01: 88 – 93.[doi: 10.33687/phytopath.001.01.0020](https://esciencepress.net/journals/index.php/phytopath/article/view/20/19)
- **_Wijerathna, Y.M.A.M._**, Kottearachchi, and Attanayaka, D.P.S.T.G. (2012). Assessment of Inter and Intra Cultivar Genetic and Phenotypic Variation in Grain Quality Characteristics of Sri Lankan Traditional Aromatic Rice (Oryza Sativa L.). Tropical Agriculturist. 160: 123 - 133.

_**Policy and Agriculture**_

- **_Wijerathna-Yapa, A._**, Henry, R.J., Dunn, M. and Beveridge, C.A., (2023). Science and opinion in decision making: A case study of the food security collapse in Sri Lanka. Modern Agriculture. 1: 142 -151. https://doi.org/10.1002/moda.18 
- Beveridge, C. A., Rameau, C., and **_Wijerathna-Yapa, A._**. (2023). Learnings from a century of apical dominance research. Journal of Experimental Botany, erad137-erad137. https://doi.org/10.1093/jxb/erad137
- Valladares García, A. P., **_Wijerathna-Yapa, A._**, Mishra, S., Or-Rashid, H., Nehra, M., Ramtekey, V., Ndah, R., Magar, M. M., Opondo, D., Sasha, Kumar, S., Swati, Tenesi, T., Bentley, A. R., & Basnet, B. R. (2022). In the pursuit of equality for women plant breeders around the world. https://doi.org/10.5281/zenodo.7385758
- **_Wijerathna-Yapa, A._**,and Pathirana, R. (2022). Sustainable Agro-Food Systems for Addressing Climate Change and Food Security. Agriculture, 12(10), 1554. https://doi.org/10.3390/agriculture12101554
- **_Wijerathna-Yapa, A._** (2017). Effect on Biodrying and Rapid Drying of Food Wastes for Biochar Manufacturing. - Agri Res & Tech 7 (5), 555722.[doi:10.19080/ARTOAJ.2017.07.555722](https://juniperpublishers.com/artoaj/ARTOAJ.MS.ID.555722.php)
- Kumarihami H.M.P.C., **_Wijerathna, Y.M.A.M._**, Beneragama, C.K.  (2017). Extending the postharvest life of cut - flowers with floral preservative: mini review. Proceedings of the National Symposium on Floriculture - Research, Department of National Botanic Gardens, Sri Lanka. 52-60.


**Theses and Reports**

- **_Wijerathna, Y.M.A.M._** 2020. Unravelling the Underlying Components of Autophagy-mediated Photomorphogenesis of Arabidopsis thaliana. (Ph.D. dissertation, The University of Western Australia). https://doi.org/10.26182/2hpj-7605
- **_Wijerathna, Y.M.A.M._** 2016. Analysis of Constitutively Active Pyrabactin Resistance1/Pyr1-like (pyl) Receptors in Early Development of Arabidopsis thaliana (M.Sc. dissertation, The Hebrew University of Jerusalem). https://www.nli.org.il/en/dissertations/NNL_ALEPH003951886/NLI
- **_Wijerathna, Y.M.A.M._** 2012. Application of Biotechnology in Intra Cellular Pathogen Diagnostic of Coconut - (Cocos nucifera L.) in Sri Lanka. Report on In-plant Training Programme. The Wayamba University of Sri Lanka.

**Preprints**

- Li, L., Duncan, O., Ganguly, D.R., Lee, C.P., Crisp, P., **_Wijerathna-Yapa, A._**, Pogson, B.J., Salih, K., - Trosch, J., Millar, A.H., and Pogson, B.J. (2021). Metabolic enzymes degraded under high light stress - maintain their proteostasis by coupled transcriptional regulation in Arabidopsis. bioRxiv.doi: https://doi.org/10.1101/2021.10.03.462903
- Li, L., Lee, C. P., **_Wijerathna-Yapa, A._**, Broda, M., Otegui, M. S., Ganguly, D.R., Pogson, B.J., and Millar. H. (2021). Defects in autophagy lead to selective in vivo changes in turnover of cytosolic and organelle proteins in roots and shoots of Arabidopsis. bioRxiv.doi: https://doi.org/10.1101/2021.04.29.441983
- **_Wijerathna-Yapa, A._**, Signorelli, S., Fenske, R., Ganguly, D.R., Stroeher, F., Li,L., Pogson, B.J., Duncan, O., and Millar. H. (2021). Autophagy promotes photomorphogenesis during seedling development in Arabidopsis in carbon limiting conditions. bioRxiv.doi: https://doi.org/10.1101/2021.03.25.437007

**Conference Papers**

- **_Wijerathna-Yapa, A._**, Fortuna, N., Cooper, M. and Beveridge, C. A. 2023. Prior knowledge-driven branching phenotype prediction for shoot architecture improvement. Prior knowledge-driven branching phenotype prediction for shoot architecture improvement. ComBio 2022, Melbourne Convention and Exhibition Centre (MCE), 27-30 September 2022.
- Fortuna, N. Z., **_Wijerathna-Yapa, A._**, and Beveridge, C. A. 2023 Modelling hormone signalling networks to better predict branching phenotypes. ComBio 2022, Melbourne Convention and Exhibition Centre (MCEC), 27-30 September 2022.
- Signorelli, S., **_Wijerathna-Yapa, A._**, Fenske, R., Ganguly, D.R., Stroeher, F., Li,L., Pogson, B.J., Duncan, O., and Millar. H. 2022.   Methylglyoxal catabolism is induced in autophagy mutants during photomorphogenesis. ASPB Plant Biology 2022, Portland, OR. United States, 9-13 July 2022. The American Society of Plant Biologists.
- **_Wijerathna-Yapa, A._**, Fenske, R., Li, L., Petereit, P., Cao, H., Stroher, E., Duncan, O,Millar, A.H. 2019. Application of Proteomics Techniques to Organelle Abundance Profiling of Arabidopsis thaliana Autophagy Mutants. Abstract presented at the ARC CoE in Plant Energy Biology Annual Forum 2019. The Alpine Hotel Thredbo Australia. June 4th - 6th 2019.
- Duncan, O., **_Wijerathna-Yapa, A._**, Millar, A.H. Protein synthesis and degradation in the night and day: how cycling abundances are established and maintained. 2019. Abstract presented at the ARC CoE in Plant Energy - Biology Annual Forum 2019. The Alpine Hotel Thredbo, Australia. June 4th - 6th 2019.
- **_Wijerathna-Yapa, A._**, Fenske, R., Li, L., Millar, A.H. 2018. Targeted Proteomics for Organelle Abundance Profiling of Arabidopsis thaliana Autophagy Mutants. Abstract presented at the ARC CoE in Plant Energy Biology Annual Forum 2018. Novotel Swan Valley Vines Resort, Australia. September 11th - 13th 2018.
- **_Wijerathna-Yapa, A._**, Mosquna, A. 2015. Screening an Arabidopsis cDNA Library for Interactor Proteins of Cyclase. The 2nd Pears Foundation Alumni Symposium in Plant Sciences. The Robert H. Smith Faculty of Agriculture, Food & Environment in Rehovot, Israel, from September 7th - 9th 2015.
- **_Wijerathna, Y.M.A.M._**, Kottearachchi, N.S., Gimhani, D.R. and Sirisena, D.N. 2011. Sri Lankan Fragrant Rice (Oryza Sativa L.) Varieties are Associated with Decreased Salt Tolerance. In: Proceedings of 11th - Agricultural Research Symposium, 20th -21st September 2011, Wayamba University of Sri Lanka, 51-55.

**Magazine Articles**

- **_Akila Wijerathna._** Agroforestry to the Fore. December 2024. 212.
- **_Akila Wijerathna._** Smart Farming Revolution. LMD. November 2024. 172.
- **_Akila Wijerathna._** Sustainability at the core. LMD. October 2024. 204.
- **_Akila Wijerathna._** Reshaping the Rural Economy. LMD. September 2024. 135.
- **_Akila Wijerathna._** Rise of Urban Farms. LMD. August 2024. 145.
- **_Akila Wijerathna._** Revitalized Farming systems. LMD. July 2024. 175.
- **_Akila Wijerathna._** Green future on the Line. LMD. June 2024. 135.
- **_Akila Wijerathna._** The Advent of Tech Farming. LMD. May 2024. 142.
- **_Akila Wijerathna._** Eco-Friendly Agri Exports. LMD. April 2024. 157.
- **_Akila Wijerathna._** Crops under the Weather. LMD. March 2024. 157.
- **_Akila Wijerathna._** Adopt Precision Farm Tech. February 2024. 129.
- **_Akila Wijerathna._** Rich Local Food Systems. LMD. January 2024. 140.
- **_Akila Wijerathna._** Preserve Crop Diversity LMD. December 2022. 187.
- **_Akila Wijerathna._** Mitigating Global Hunger. LMD. November 2023. 135.
- **_Akila Wijerathna._** Precision Farming Mantra. LMD. October 2023. 142.
- **_Akila Wijerathna._** Global Food Security Pangs. LMD. September 2023. 205.
- **_Akila Wijerathna._** Champions of Sustainability. LMD. August 2023. 133.
- **_Akila Wijerathna._** Smallholder Diversification. LMD. July 2023. 179.
- **_Akila Wijerathna._** Climate Smart Farming. LMD. June 2023. 134.
- **_Akila Wijerathna._** Sustainable Urban Gardens. LMD. May 2023. 125.
- **_Akila Wijerathna._** Crops Prop Food Security. LMD. April 2023. 140.
- **_Akila Wijerathna._** Smallholders' major roles. LMD. March 2023. 184.
- **_Akila Wijerathna._** Wanted: Agronomy Measures. February 2023. 143.
- **_Akila Wijerathna._** Risk of Worldwide Hunger. LMD. January 2023. 131
- **_Akila Wijerathna._** Farming needs reimagining. LMD. December 2022. 141.
- **_Akila Wijerathna._** Climate and Agriculture. LMD. November 2022. 138.
- **_Akila Wijerathna._** Zero Hunger — The End Goal. LMD. October 2022. 135.
- **_Akila Wijerathna._** Farming without farmland. LMD. September 2022. 148.
- **_Akila Wijerathna._** Flowering of a Green Idea. LMD. August 2022. 147.
- **_Akila Wijerathna._** Farming and Supply Chains. LMD. July 2022. 178.
- **_Akila Wijerathna._** Big Challenges Small Farms. LMD. June 2022. 142.
- **_Akila Wijerathna._** Going Green: The smart way. LMD. May 2022. 124.
- **_Akila Wijerathna._** Gains from the Smart Farming. LMD. April 2022. 114.
- **_Akila Wijerathna._** Biotechnology's Golden Era. LMD. March 2022. 183.
- **_Akila Wijerathna._** Piggybacking on Agriculture. LMD. February 2022. 137.
- **_Akila Wijerathna._** Supply Chain Disruptions. LMD. January 2022. 144.
- **_Akila Wijerathna._** Post-COVID food security. LMD. December 2021. 184.
- **_Akila Wijerathna._** Pest control in Agri-Food. LMD. November 2021. 115.
- **_Akila Wijerathna._** AI and Climate Emergencies. LMD. October 2021. 69.
- **_Akila Wijerathna._** Bio-based farm economy. LMD. September 2021. 132.
- **_Akila Wijerathna._** Bridging the Gender Gap. LMD. August 2021. 138.
- **_Akila Wijerathna._** Climate Crisis and Farming. LMD. July 2021. 174.
- **_Akila Wijerathna._** Indoor Farming Takes Root. LMD. June 2021. 126.
- **_Akila Wijerathna._** Green Energy for Crops. LMD. May 2021. 144.
- **_Akila Wijerathna._** Mitigating farming risks. LMD. April 2021. 137.
- **_Akila Wijerathna._** Protecting the Planet. LMD. March 2021. 155.
- **_Akila Wijerathna._** The Urban-Rural Divid. LMD. February 2021. 117.
- **_Akila Wijerathna._** Innovating for Security. LMD. January 2021. 150.
- **_Akila Wijerathna._** Next Generation Production. LMD. December 2020. 132.
- **_Akila Wijerathna._** Combating land degradation. LMD. November 2020. 129.
- **_Akila Wijerathna._** Resourceful conservation in the agriculture sector. LMD. October 2020. 122.
- **_Akila Wijerathna._** The food system woes unearthed by the pandemic. LMD. - September 2020. 164.
- **_Akila Wijerathna._** The pursuit of equality. LMD. August 2020. 144.
- **_Akila Wijerathna._** Ecological Intensification. LMD. July 2020. 128.
- **_Akila Wijerathna._** The Farming Transformation. LMD. - June 2020. 116.
- **_Akila Wijerathna._** Next Generation Farming. LMD. - May 2020. 116.
- **_Akila Wijerathna._** Smallholder development. LMD. - April 2020. 150.
- **_Akila Wijerathna._** Climate Change Proofing. LMD. March 2020. 160.
- **_Akila Wijerathna._** Dispels umpteen misconceptions associated with agriculture. LMD. February 2020. 142.
- **_Akila Wijerathna._** Sustainable Collaboration to develop a sustainable global food system. LMD. - January 2020. 190.
- **_Akila Wijerathna._** The Smallholder Challenge. LMD. December 2019. 174.
- **_Akila Wijerathna._** Agro's Digital Revolution. LMD. November 2019. 176.
- **_Akila Wijerathna._** Investing in Development. LMD. October 2019. 169.
- **_Akila Wijerathna._** Sustainable Transformation. - LMD. September 2019. 145.
- **_Akila Wijerathna._** Unpeels the economic benefits of commercializing a fruit!. LMD. August 2019. 136.
- **_Akila Wijerathna._** The Gender Gap in Farming. LMD. July 2019. 193.
- **_Akila Wijerathna._** Develop Genetic Diversity. LMD. - June 2019. 167.
- **_Akila Wijerathna._** Genetically Engineered DNA. LMD. May 2019. 171.
- **_Akila Wijerathna._** Growing Community Gardens. LMD. April 2019. 139.
- **_Akila Wijerathna._** The Food Security Crunch. LMD. March 2019. 155.
- **_Akila Wijerathna._** The Rise of Smart Foods. LMD. February 2019. 168.
- **_Akila Wijerathna._** Rescue Act for Food Waste. LMD. January 2019. 160.
- **_Akila Wijerathna._** Crop Protection Solutions. LMD. December 2018. 168.
- **_Akila Wijerathna._** Untapped Biotech Potential. LMD. November 2018. 197.
- **_Akila Wijerathna._** Holistic Farming Practice. LMD. October 2018. 181.
- **_Akila Wijerathna._** The Maze of Biotechnology. LMD. September 2018. 181.
- **_Akila Wijerathna._** Post Harvest Losses. LMD. August 2018. 175.
- **_Akila Wijerathna._** Organic Farming. LMD. July 2018. 229.
- **_Akila Wijerathna._** Digital Farming. LMD. June 2018. 172.
- **_Akila Wijerathna._** The Science of Sharing. LMD. May 2018. 213.
- **_Akila Wijerathna._** Saving the Plants from Stress. LMD. April 2018. 166.
- **_Akila Wijerathna._** The Future of Agriculture. LMD. March 2018. 202.
- **_Akila Wijerathna._** Waste from Green Field. LMD. February 2018. 172.
- **_Akila Wijerathna._** Family Farming: Breaking the Cycle. LMD. January 2018. 178.
- **_Akila Wijerathna._** Floriculture Sector. LMD. December 2017:198.
- **_Akila Wijerathna._** Agriculture Revival: Organic Farming. LMD. November 2017:235.
- **_Akila Wijerathna._** The Fruits of Agriculture. LMD. October 2017:209.
- **_Akila Wijerathna._** Food Safety: Critical Conscience. LMD. August 2017:182.
- **_Akila Wijerathna._** Farm Biodiversity: Shared Responsibility. LMD. July 2017:165.
- **_Akila Wijerathna._** Urban Ecosystems: The Trees of City Life. LMD. June 2017:206.
- **_Akila Wijerathna._** Food Safety: Better Safe Than Sorry. LMD. May 2017:174. 
- **_Akila Wijerathna._** Farmers' Markets. LMD. April 2017:194. 
- **_Akila Wijerathna._** Small Holder Agriculture. LMD. March 2017: 182.
- **_Akila Wijerathna._** Women in Farming. LMD. February 2017: 206.
- **_Akila Wijerathna._** Start-up Farming. LMD. January 2017: 190.
- **_Akila Wijerathna._** Future-Ready Farming Techniques. LMD. December 2016: 222.
- **_Akila Wijerathna._** The Seed of Organic Farming. LMD. November 2016: 220.
- **_Akila Wijerathna._** Urban Agriculture. LMD. Oct 2016: 220.
- **_Akila Wijerathna._** Smart Agriculture: Inclusive farming. LMD. Sep 2016: 203.
- **_Akila Wijerathna._** Empowering Farmers. LMD. August 2016: 210.
- **_Akila Wijerathna._** Farming for Tomorrow. LMD. July 2016: 236.
- **_Akila Wijerathna._** Crop Enabler: Genetic Engineering. LMD. June 2016: 222.
- **_Akila Wijerathna._** Biotech Ethics: Roadblocks to Research. LMD. May 2016: 187.
- **_Akila Wijerathna._** Farming Boost From Biotech. LMD. April 2016: 182.
- **_Akila Wijerathna._** Biodynamic Agriculture. LMD. March 2016: 212.
- **_Akila Wijerathna._** Harnessing Biotech for Livestock. LMD. February 2016: 195.
- **_Akila Wijerathna._** The Bio-Economy. LMD. January 2016: 185.
- **_Akila Wijerathna._** Unravels the truth behind GMO. LMD. December 2015: 233.
- **_Akila Wijerathna._** Sowing the seeds of productivity. LMD. November 2015: 174.
- **_Akila Wijerathna._** BIOTECH for Business. LMD. October 2015: 166.
- **_Akila Wijerathna._** The Ethics of Food Supply. LMD. September 2015: 193.
- **_Akila Wijerathna._** Protecting the Planet Earth. LMD. August 2015: 182.
- **_Akila Wijerathna._** Tree Conservation: Blooming City. LMD. July 2015: 192.
- **_Akila Wijerathna._** Farm tourism: regenerating tourism. LMD. June 2015: 195.
- **_Akila Wijerathna._** Unearth development in rice biotechnology. LMD. May 2015: 166.
- **_Akila Wijerathna._** In Search of Zero Waste. LMD. - March 2015: 169.