---
title: "Symposia & Workshops"
---


**Symposia**

- ARC CoE in Plant Energy Biology Annual Forum 2018. “Building Tangible Improvements to Energy Use Efficiency - in Plants”. Novotel Swan Valley Vines Resort – Australia. September 11th -13th 2018.
- ARC CoE in Plant Energy Biology Annual Forum 2017. “Building and Extending Collaborative Projects”. - Adelaide Hills Convention Centre – Australia. May 8th – 11th 2017.
- 17th Otto Warburg symposium. “Next Generation Plant Biotechnology”. The Robert H. Smith Faculty of - Agriculture, Food and Environment. The Hebrew University of Jerusalem, Israel. April 11th -13th 2016.
- The 2nd Pears Foundation Alumni Symposium in Plant Sciences, entitled "Knowledge Sharing - A Key for - Enhancing Agricultural Productivity". The Robert H. Smith Faculty of Agriculture, Food & Environment in - Rehovot, Israel, from September 7th-9th, 2015.
- The 2nd International Symposium on Agriculture and Environmental Health. The Robert H. Smith Faculty of - Agriculture, Food and Environment. The Hebrew University of Jerusalem, Israel. May 28th, 2015
- The 5th The International Conference on Drylands, Deserts, and Desertification (DDD) conference. Ben-Gurion - University of the Negev, Israel. 17th -20th November 2014.
- The 11th Agricultural Research Symposium (AGRES). Wayamba University of Sri Lanka, from 20th -21st of - September 2011.

**Presentations**

- **Akila Wijerathna-Yapa.** 06th May 2019. Determining the Contribution of Autophagy to Protein Turnover of - Energy Organelles in Arabidopsis thaliana.  European Molecular Biology Organization (EMBO) Practical - Course: Quantitative Proteomics: Strategies and Tools to Probe Biology taking place at EMBL Heidelberg, - Germany.
- **Akila Wijerathna-Yapa.** 13th September 2018. Targeted Proteomics for Organelle Abundance Profiling of - Arabidopsis thaliana Autophagy Mutants. ARC CoE in Plant Energy Biology Annual Forum 2018. Novotel Swan - Valley Vines Resort – Australia. September 13th, 2018.
- **Akila Wijerathna-Yapa.** 04th April 2018. Autophagy: Bringing together divergent topics in organelle - biology? ARC Centre of Excellence in Plant Energy Biology Seminar, the University of Western Australia.
- **Akila Wijerathna-Yapa.** 04th August 2017. Studying the First Derivative of Proteomics: What is protein - turnover tells us and what are the challenges ahead? ARC Centre of Excellence in Plant Energy Biology - Seminar, the University of Western Australia.
- **Akila Wijerathna-Yapa.** 26th June 2017. Determining the contribution of autophagy to protein turnover - rate of energy organelles in the model plant Arabidopsis. Ph.D. Proposal Symposium. School of Molecular - Sciences, the University of Western Australia.
- **Akila Wijerathna-Yapa.** 06th September 2016. Screening an Arabidopsis cDNA Library for Interactor - Proteins of Cyclase. The 2nd Pears Foundation Alumni Symposium in Plant Sciences: "Knowledge Sharing - A - Key for Enhancing Agricultural Productivity" at the Robert H. Smith Faculty of Agriculture, Food & - Environment in Rehovot, Israel.
- **Akila Wijerathna-Yapa.** 20th September 2011. Sri Lankan Fragrant Rice (Oryza Sativa L.) Varieties are - Associated with Decreased Salt Tolerance. The 11th Agricultural Research Symposium (AGRES), Wayamba - University of Sri Lanka.

**Workshops**

- University Learning and Teaching professional development program: SPARK (Skills, Pedagogical Approaches, - Resources, and Knowledge). The University of Western Australia (2019).
- The Research Bazaar (digital literacy emerging at the centre of modern research) at Curtin University, - Australia (2nd – 4th July 2019).
- Quantitative Proteomics: Strategies and Tools to Probe Biology at the European Molecular Biology - Organization (EMBO) EMBL Heidelberg, Germany (5th May – 10th May 2019).  
- Concept to Creation (C2C). The Centre for Entrepreneurial Research and Innovation (CERI) (21st March – 4th - July 2019).
- Entrepreneurial Mindset Boot Camp. The Centre for Entrepreneurial Research and Innovation (CERI) (22nd-23rd - October 2018).
- Unsealed Radioisotopes Handling Course. Safety, Health & Wellbeing, The University of Western Australia - (24th - 26th July 2018).
- Data Visualization. Centre for Applied Statistics, the University of Western Australia (17th July 2018).
- R Basics. Centre for Applied Statistics, the University of Western Australia. (3rd -4th July 2018)
- ANOVA, Linear regression, and Logistic Regression. Centre for Applied Statistics, the University of Western - Australia (10th -12th July 2018).
- Consumer and Community Involvement in Research workshop at the School of Population and Global Health, the - University of Western Australia (2 July 2018).
- Introductory Statistics. Centre for Applied Statistics, the University of Western Australia (26th -28th - June 2018).
- Graduate Research School Workshop: Academic Writing (Science/Applied Science) at the University of Western - Australia (21 March 2018).
- Laboratory Safety Course. Safety, Health and Wellbeing Safety Training at the University of Western - Australia (6th March 2018)
- The Research Bazaar (software-carpentry) at the University of Western Australia (23rd – 25th January 2018).
- Graduate Research School Workshop: THESIS AS SERIES OF PAPERS (Science/Applied Science) at the University - of Western Australia.
- Laboratory Safety Course. Safety, Health, and Wellbeing Safety Training at the University of Western - Australia (24th July 2017).
- Completed iBiology© iBio1 Certificate: Planning Your Scientific Journey.
- Graduate Research School Workshop: Writing a Journal Article at the University of Western Australia.
- Graduate Research School Workshop: Thesis Structures in The Sciences/ Applied Sciences at the University of - Western Australia.
- Graduate Research School Workshop: Using Microsoft Word for Thesis Writing at the University of Western - Australia.
- Israel-Canada workshop on Advanced Biofuels at The Robert H. Smith Faculty of Agriculture, Food and - Environment, The Hebrew University of Jerusalem, Israel. 8-9th November 2015.
- National Science & Technology Commission workshop on Experimental Design at Postgraduate Institute of - Agriculture, University of Peradeniya. (9th September 2014).
- National Key Facility for Crop Gene Resources and Genetic Improvement. Development of Agricultural Science - in China, Brassica Genome Sequencing. The Institute of Crop Science, CAAS, Beijing 100081, PR China. - (September 2013 –April 2014). 